# Netlify build configuration
[build]
  publish = "dist"  # Folder where your build output is stored
  command = "npm run build"  # Command to build your app
  base = "./"  # Adjust if necessary

[build.environment]
  NODE_VERSION = "20.17.0"  # Specify the Node.js version if needed
  MONGO_URI = "your-mongo-uri"  # MongoDB URI (ensure it's secure)

[functions]
  directory = "netlify/functions"  # Folder where your Netlify functions are located

[dev]
  functions = "netlify/functions"  # Local dev server settings
  autoLaunch = true
  command = "npm start"
  port = 3000
  targetPort = 4000

# Single [headers] block containing all header rules
[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  status = 200
