# Netlify build configuration
[build]
  publish = "dist"  # Ensure this matches your actual build output folder
  command = "npm run build"
  base = "C:\\Users\\pusel\\township-business-directory\\.netlify"  # Local base path (adjust if needed)

[build.environment]
  NODE_VERSION = "20.17.0"  # Example: specify the Node.js version
  MONGO_URI = "mongodb+srv://puseletso55:Daniel@9615@townshipbusinesschatbot.awtrt6h.mongodb.net/?retryWrites=true&w=majority&appName=TownshipBusinessChatbot"  # MongoDB URI

[functions]
  directory = "netlify/functions"  # Folder where your Netlify functions are located

[dev]
  functions = "netlify/functions"  # Local dev server settings
  autoLaunch = true
  command = "npm start"
  port = 3000
  targetPort = 4000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  status = 200

[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
