# Netlify build configuration
[build]
  # Folder where your build output is stored
  publish = "dist"  # Ensure this matches your actual build output folder
  # Command to build your app
  command = "npm run build"
  base = "./"  # Adjust if necessary

[build.environment]
  NODE_VERSION = "20.17.0"  # Specify the Node.js version if needed
  MONGO_URI = "MONGO_URI=mongodb+srv://puseletso55:Daniel@9615@townshipbusinesschatbot.awtrt6h.mongodb.net/?retryWrites=true&w=majority&appName=TownshipBusinessChatbot"  # MongoDB URI (ensure it's secure)

[functions]
  # Folder where your Netlify functions are located
  directory = "netlify/functions"  # Ensure this folder exists in your project

[dev]
  # Local dev server settings
  functions = "netlify/functions"  # Local dev server settings
  autoLaunch = true
  command = "npm start"
  port = 3000
  targetPort = 4000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  status = 200

[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
