[build]
  # Specify the directory for the build output (e.g., if you're using Vite, this would be the build folder)
  publish = "C:\\Users\\pusel\\township-business-directory\\.netlify\\dist"  # Local path (you can adjust this if necessary)
  command = "npm run build"
  
  # If you're using the "ui" folder for the build origin, ensure it's properly set
  base = "C:\\Users\\pusel\\township-business-directory\\.netlify"  # Local base path (adjust if needed)

[build.environment]
  # Add any environment variables here (if required)

[functions]
  # Specify the folder where your Netlify functions are located
  directory = "C:\\Users\\pusel\\township-business-directory\\.netlify\\netlify\\functions"  # Local path (adjust if needed)

[dev]
  # Local dev server settings (optional)
  functions = "netlify/functions"
  autoLaunch = false

# Redirects and headers (if needed)
[redirects]
  # Add redirect rules here if necessary (e.g., URL redirects)
  
[headers]
  # Add custom headers here (e.g., for caching, security)
